import argparse
from contextvars import ContextVar
import json
from os import PathLike
import os
from pathlib import Path
import re
import shutil
import subprocess
import time
from typing import TYPE_CHECKING, Callable

import colorama
import httpx

from dome import core
from dome.model import Model
from dome import tech


class ProjectFunctionContext(Model):
    id: str
    tech: str
    shortid: str
    name: str | None
    description: str | None

    args: argparse.Namespace
    cwd: Path
    version: str
    debug: bool
    mode: str
    projectfile: Path
    build_dir: Path
    source: Path

    class Config:
        arbitrary_types_allowed = True


_project_function_context = ContextVar("project_function_context")
call = core.call


# called internally
def _set_context(c: ProjectFunctionContext):
    _project_function_context.set(c)


def context() -> ProjectFunctionContext:
    return _project_function_context.get()


def generate_build_info():
    ctx = context()
    build_time = time.time()
    extension = tech.get_extension(ctx.tech)
    target = Path(f"build.{extension}")

    print(f"Generate build info to '{target}'.")
    target = Path(ctx.source, target)
    extension = target.suffix.removeprefix(".")
    auto_message = f"AUTO-GENERATED BY THE BUILD SYSTEM. Edit responsibly."
    content = ""
    if extension == "py":
        content = f"# {auto_message}\nproject_id = \"{ctx.id}\"\nversion = \"{ctx.version}\"\ntimestamp = {build_time}\ndebug = {'True' if ctx.debug else 'False'}"
    elif extension in ["js", "ts"]:
        BRACKET_LEFT = "{"
        BRACKET_RIGHT = "}"
        content = f"// {auto_message}\nconst project_id = \"{ctx.id}\";\nconst version = \"{ctx.version}\";\nconst timestamp = {build_time};\nconst debug = {'true' if ctx.debug else 'false'};\nexport {BRACKET_LEFT} project_id, version, timestamp, debug {BRACKET_RIGHT};\n"
    else:
        raise Exception(f"Unsupported build info extension '{extension}' at location '{target}'.")
    with target.open("w+") as f:
        f.write(content)


# @todo we also need to use glob as target, like `buildInclude("*.html")`, but in such a case we should disallow `dest`
def include(target: Path | str, dest: Path | str | None = None):
    """
    Includes target into a build directory.
    """
    ctx = context()
    target = Path(target)
    real_target = Path(ctx.source, target)

    message = f"Include target '{target}'."
    if dest:
        message += f" Destination is altered to '{dest}'."
    print(message)

    if not real_target.exists():
        raise Exception(f"Cannot find include path '{real_target}'.")
    elif real_target.is_dir():
        if dest == ".":
            # We cannot just copytree, or an "already-existing" error will be raised. Instead, we will copy everything from the target directory to the build directory.
            for item in os.listdir(real_target):
                item_path = Path(real_target, item)
                dest_path = Path(ctx.build_dir, item)
                if item_path.is_dir():
                    shutil.copytree(item_path, dest_path)
                else:
                    shutil.copy2(item_path, dest_path)
        else:
            shutil.copytree(real_target, Path(ctx.build_dir, dest if dest else target))
    else:
        if dest == ".":
            raise Exception(f"Include destination of '.' is not allowed for files.")
        shutil.copy2(real_target, Path(ctx.build_dir, dest if dest else target))


class Host:
    """
    Provides functionality to interact with remote machines.
    """
    def __init__(self, host: str):
        self._host: str = host
        self._executor_secret: str | None = None
        self._user: str | None = None

    def setExecutorSecret(self, secret: str):
        self._executor_secret = secret

    def setUser(self, user: str):
        self._user = user

    def scp(self, from_path: PathLike, to_path: PathLike, *, port: int = 22):
        if not self._user:
            raise Exception(f"please set user first using a function `host.setUser()`")

        ctx = context()
        project_source = ctx.source

        from_path = Path(project_source, from_path)
        to_path = Path(to_path)
        command = f"scp -r -P {port} {from_path.resolve()} {self._user}@{self._host}:{str(to_path).replace('\\', '/')}"
        print(f"[host {self._host}] " + command)
        _, stderr, retcode = call(command)
        if retcode != 0:
            raise Exception(f"[host {self._host}] scp failed with retcode {retcode} and error {stderr}")

    def request(self, url: str, **kwargs) -> httpx.Response:
        return httpx.post(url, **kwargs)

    def mustExecute(self, command: str, **kwargs) -> tuple[str, str]:
        retcode, stdout, stderr = self.execute(command, **kwargs)
        if retcode != 0:
            raise Exception(f"retcode {retcode} while executing command '{command}', with stderr {stderr}")
        return stdout, stderr

    def execute(self, command: str, *, background: bool = False, cwd: str | None = None, port: int = 6650) -> tuple[int, str, str]:
        """
        Executes a command on the remote server, using `executor` service.
        """
        if not self._executor_secret:
            raise Exception(f"please set executor secret first using a function `host.setExecutorSecret()`")
        payload = {
            "command": command,
            "background": background,
        }
        if cwd:
            payload["cwd"] = cwd

        response_message = f"[host {self._host}] execute command '{command}'"
        if background:
            response_message += f", background {background}"
        if port != 6650:
            response_message += f", port {port}"
        if cwd is not None:
            response_message += f", cwd '{cwd}'"
        print(response_message)

        r = self.request(f"http://{self._host}:{port}/main/execute", json=payload, headers={"secret": self._executor_secret})
        if r.status_code != 200:
            raise Exception(f"status error while executing: status {r.status_code}, text {r.text}")

        code, data = core.unwrap_coded_structure(r.content)
        if code != 0:
            data = data.decode()
            raise core.CodeError(1, f"code error while executing: code {code}, text {data}")

        data = json.loads(data)
        retcode = data["retcode"]
        stdout = data["stdout"]
        stderr = data["stderr"]
        return retcode, stdout, stderr