# PathLike | str combination is used due to problems with Pylance

import argparse
from contextvars import ContextVar
import json
from os import PathLike
import os
from pathlib import Path
import re
import shutil
import subprocess
import tarfile
import time
from typing import TYPE_CHECKING, Callable

import colorama
import httpx

from dome import core
from dome.model import Model
from dome.project import Project


__all__ = [
    "Project",
    "Model",
]


_projectfile_context = ContextVar("project_function_context")


# called internally
def _set_project(c: Project):
    _projectfile_context.set(c)


def project() -> Project:
    return _projectfile_context.get()


def init_build():
    p = project()
    shutil.rmtree(p.build_dir, ignore_errors=True)
    p.build_dir.mkdir(parents=True, exist_ok=True)


def generate_build_info(target: PathLike | str):
    p = project()
    build_time = time.time()

    print(f"Generate build info to '{target}'.")
    target = Path(p.source_dir, target)
    extension = target.suffix.removeprefix(".")
    auto_message = f"Auto-Generated by the Dome Build System. Edit responsibly."
    content = ""
    if extension == "py":
        content = f"# {auto_message}\nid = \"{p.id}\"\nversion = \"{p.version}\"\ntime = {build_time}\ndebug = {'True' if p.debug else 'False'}"
    elif extension in ["js", "ts"]:
        BRACKET_LEFT = "{"
        BRACKET_RIGHT = "}"
        content = f"// {auto_message}\nconst id = \"{p.id}\";\nconst version = \"{p.version}\";\nconst time = {build_time};\nconst debug = {'true' if p.debug else 'false'};\nexport {BRACKET_LEFT} id, version, time, debug {BRACKET_RIGHT};\n"
    else:
        raise Exception(f"Unsupported build info extension '{extension}' at location '{target}'.")
    with target.open("w+") as f:
        f.write(content)


def generate_codes(target: PathLike | str):
    """
    Builds a codesheet.

    Built codesheet includes a programming-language-specific compile-time (or boot-time) constant definitions, and a dictionary-like definition, where the keys are codes, and the values are codenames.
    """
    codename_rules = """{ind}1. alphanumeric
{ind}2. lower case
{ind}3. separated by underscores
{ind}4. not starting with an underscore
{ind}5. not ending with an underscore
{ind}6. not starting with a digit"""
    indentation = "    "

    p = project()
    codes = []
    # note that we always search `code.txt` under the current working directory...
    code_path = Path(p.cwd, "code.txt")
    # ... or under the parent
    if not code_path.exists():
        code_path = Path(p.cwd, "../code.txt")

    if code_path.exists():
        with code_path.open("r") as file:
            lines = file.readlines()
            for line in lines:
                line = line.strip().lower()
                # Codes must be parsed strictly. We want our `codes.txt` file to look clean.
                # We add even empty lines - codes must be correctly enumerated. Later empty lines will be replaced by empty lines during code-file generation.
                if line:
                    if line in ["ok", "codenames"]:
                        raise Exception(f"Cannot use reserved codename '{line}'.")
                    if not re.match(r"^(?![0-9])(?<!_)([a-z0-9]+(?:_[a-z0-9]+)*)[^_]$", line):
                        raise Exception(f"Invalid codename: '{line}'. Codename rules:\n{codename_rules.format(ind=indentation)}")
                    if line in codes:
                        raise Exception(f"Duplicate definition of a codename '{line}'.")

                codes.append(line)

    print(f"Generate codes.")
    target = Path(p.source_dir, target)
    extension = target.suffix.removeprefix(".")
    content = ""
    codenames = ""
    # Codes must be already valid at this point.
    if extension == "py":
        content += "ok = 0\n"
        for code, codename in enumerate(codes):
            code += 1
            content += f"{codename} = {code}\n"
            codenames += f"{indentation}{code}: \"{codename}\",\n"

        content += """
codenames: dict[int, str] = {{
{codenames}}}""".format(codenames=codenames)

    elif extension in ["js", "ts"]:
        content += "export const ok = 0;\n"
        for code, codename in enumerate(codes):
            code += 1
            content += f"export const {codename} = {code};\n"
            codenames += f"{indentation}{code}: \"{codename}\",\n"

        content += """
export const codenames = {{
{codenames}}};""".format(codenames=codenames)

    else:
        raise Exception(f"Unsupported codes extension '{extension}' at location '{target}'.")
    with target.open("w+") as f:
        f.write(content)


# @todo we also need to use glob as target, like `buildInclude("*.html")`, but in such a case we should disallow `dest`
def include(target: Path | str, dest: Path | str | None = None):
    """
    Includes target into a build directory.
    """
    ctx = project()
    target = Path(target)
    real_target = Path(ctx.source_dir, target)

    message = f"Include target '{target}'."
    if dest:
        message += f" Destination is altered to '{dest}'."
    print(message)

    if not real_target.exists():
        raise Exception(f"Cannot find include path '{real_target}'.")
    elif real_target.is_dir():
        if dest == ".":
            # We cannot just copytree, or an "already-existing" error will be raised. Instead, we will copy everything from the target directory to the build directory.
            for item in os.listdir(real_target):
                item_path = Path(real_target, item)
                dest_path = Path(ctx.build_dir, item)
                if item_path.is_dir():
                    shutil.copytree(item_path, dest_path)
                else:
                    shutil.copy2(item_path, dest_path)
        else:
            shutil.copytree(real_target, Path(ctx.build_dir, dest if dest else target))
    else:
        if dest == ".":
            raise Exception(f"Include destination of '.' is not allowed for files.")
        shutil.copy2(real_target, Path(ctx.build_dir, dest if dest else target))


def include_python():
    p = project()
    for root, dirs, files in os.walk(p.source_dir):
        if Path(root) == p.source_dir:
            for filename in files:
                # include requirements and all python filenames
                if filename in "requirements.txt" or filename.endswith(".py"):
                    include(filename)
        # search only top-level modules to include
        elif Path(root).parent == p.source_dir:
            for filename in files:
                if filename == "__init__.py":
                    include(Path(root).name)


class Host:
    """
    Provides functionality to interact with remote machines.
    """
    def __init__(self, host: str):
        self._host: str = host
        self._executor_secret: str | None = None
        self._user: str | None = None

    def set_executor_secret(self, secret: str):
        self._executor_secret = secret

    def set_user(self, user: str):
        self._user = user

    def scp(self, from_path: PathLike | str, to_path: PathLike | str, *, port: int = 22):
        if not self._user:
            raise Exception(f"please set user first using a function `host.setUser()`")

        ctx = project()
        project_source = ctx.source_dir

        from_path = Path(project_source, from_path)
        to_path = Path(to_path)
        command = f"scp -r -P {port} {from_path.resolve()} {self._user}@{self._host}:{str(to_path).replace('\\', '/')}"
        print(f"[host {self._host}] " + command)
        _, stderr, retcode = call(command)
        if retcode != 0:
            raise Exception(f"[host {self._host}] scp failed with retcode {retcode} and error {stderr}")

    def request(self, url: str, **kwargs) -> httpx.Response:
        return httpx.post(url, **kwargs)

    def must_execute(self, command: str, **kwargs) -> tuple[str, str]:
        retcode, stdout, stderr = self.execute(command, **kwargs)
        if retcode != 0:
            raise Exception(f"retcode {retcode} while executing command '{command}', with stderr {stderr}")
        return stdout, stderr

    def execute(self, command: str, *, background: bool = False, cwd: str | None = None, port: int = 6650) -> tuple[int, str, str]:
        """
        Executes a command on the remote server, using `executor` service.
        """
        if not self._executor_secret:
            raise Exception(f"please set executor secret first using a function `host.setExecutorSecret()`")
        payload = {
            "command": command,
            "background": background,
        }
        if cwd:
            payload["cwd"] = cwd

        response_message = f"[host {self._host}] execute command '{command}'"
        if background:
            response_message += f", background {background}"
        if port != 6650:
            response_message += f", port {port}"
        if cwd is not None:
            response_message += f", cwd '{cwd}'"
        print(response_message)

        r = self.request(f"http://{self._host}:{port}/main/execute", json=payload, headers={"secret": self._executor_secret})
        if r.status_code != 200:
            raise Exception(f"status error while executing: status {r.status_code}, text {r.text}")

        code, data = core.unwrap_coded_structure(r.content)
        if code != 0:
            data = data.decode()
            raise core.CodeError(1, f"code error while executing: code {code}, text {data}")

        data = json.loads(data)
        retcode = data["retcode"]
        stdout = data["stdout"]
        stderr = data["stderr"]
        return retcode, stdout, stderr


def tar(source_dir: PathLike | str, output_filename: PathLike | str):
    """Create a .tar.gz archive from the specified directory."""
    p = project()
    with tarfile.open(Path(p.source_dir, output_filename), "w:gz") as tar:
        tar.add(Path(p.source_dir, Path(p.source_dir, source_dir)), arcname=os.path.basename(source_dir))


def untar(tar_gz_path: PathLike | str, extract_path: PathLike | str):
    """Extract a .tar.gz archive to the specified directory."""
    p = project()
    with tarfile.open(Path(p.source_dir, tar_gz_path), "r:gz") as tar:
        tar.extractall(path=Path(p.source_dir, extract_path))


def trash(*paths: PathLike | str):
    """Universal trash command."""
    p = project()
    new_paths = []
    for path in paths:
        new_paths.append(Path(p.source_dir, path))
    call(f"~/.app/trash/trash.py trash {' '.join([str(x) for x in new_paths])}", p.source_dir)


def rm(*paths: PathLike | str):
    p = project()
    new_paths = []
    for path in paths:
        new_paths.append(Path(p.source_dir, path))
    call(f"rm -rf {' '.join([str(x) for x in new_paths])}", p.source_dir)


def call(command: str, dir: PathLike | str | None = None) -> tuple[str, str, int]:
    p = project()
    if dir is None:
        d = p.source_dir
    else:
        d = Path(p.source_dir, dir)
    return core.call(command, d)


def must_call(command: str, dir: PathLike | str | None = None):
    p = project()
    _, stderr, retcode = call(command, dir)
    if retcode != 0:
        raise Exception(f"During call of command '{command}', an error occurred: {stderr}")